### ISSUE TITLE
Indent guide not shown

### ISSUE THREAD

**Issue by Binocular222** [SammaySarkar/XYplorer#1]
Indent guide is not shown even though I have 
>"draw_indent_guides": true,

**Comment by SammaySarkar** [comment]
Weird. I get them... :confused: 
I'll check if my indents are artificially applied by some other plugin.

**Comment by SammaySarkar** [comment]
ed. Yep. They're still there in a fresh ST config with only XYplorer pkg installed. (hilited in the img)

![indentguides](https://cloud.githubusercontent.com/assets/3525376/7550914/940b967e-f696-11e4-9b32-d03bbf176eb5.png)

Maybe some conflicting package, or perhaps your color theme makes them faint?
Also, note that this setting `"indent_guide_options":` has to be filled with at least one option.

**Comment by Binocular222** [comment]
Found it, it's due to I use Tab.
Indent guide is only shown if using spaces. Weird.

**Comment by SammaySarkar** [comment]
Well, ST itself seems to be responsible for this. I converted a json file indentation to tabs and it's inner indentguides disappeared.

Nothing wrong with this pkg. Issue can be closed now.

**Comment by Binocular222** [comment]
That was fixed since ST 3 build 3086. What a prompt action from Jon!
